version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0 # specifically, a docker image with ruby 2.4.1
    steps:
      - checkout # this pulls code down from GitHub
      - run: echo "Hello" # This prints "A first hello" to stdout.
      - run: sleep 2 # a command telling the job to "sleep" for 1 second.
  two: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "World" # We run a similar echo command to above.
      - run: echo $ENGINEER " | "  $CIRCLE_WORKFLOW_ID " | "  $CIRCLE_WORKFLOW_ID
      
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
    one_and_two: # this is the name of our workflow
      jobs: # and here we list the jobs we are going to run.
        - welcome/run
        - one
        - two:
            requires:
              - one